#- hosts: raspbian_all
#  remote_user: pi
#  become: yes
#  gather_facts: no
#  tasks:
#    - name: set github email
#      git_config:
#        name: user.email
#        scope: global
#        value: mortyone@hotmail.com

#    - name: set github user name
#      git_config:
#        name: user.name
#        scope: global
#        value: '{{ ansible_hostname }}'




#- hosts: raspbian_desktop
#  remote_user: pi
#  become: yes
#  roles:
#    - role: git
#      repo: mortyone/Pictures
#      dest: /home/pi/Pictures
#      version: main



- hosts: k3s_master
  remote_user: pi
  become: yes
  gather_facts: no

  pre_tasks:
    - name: add ansible aliases
      lineinfile:
        path: /home/pi/.bashrc
        line: '{{ item }}'
        state: present
      with_items:
        - alias ap="ansible-playbook "
        - 'alias al="ansible-lint "'

    - name: create github directory
      ansible.builtin.file:
        path: /home/pi/github
        state: directory


  roles: 
    - role: git
      repo: mortylabs/ansible
      dest: /home/pi/github/ansible
      version: main

    - role: git
      repo: mortyone/systemd-services
      dest: /home/pi/github/ansible/roles/systemd/files
      version: master

    - role: git
      repo: mortylabs/MultiRFLinkTCPBridge
      dest: /home/pi/github/MultiRFLinkTCPBridge
      version: main

    - role: git
      repo: mortyone/Music
      dest: /home/pi/Music
      version: main

    - role: git
      repo: mortyone/python
      dest: /home/pi/python
      version: master

    - role: git
      repo: mortyone/kubernetes
      dest: /home/pi/nfs/k8s
      version: main

    - role: git
      repo: mortyone/k8sbak_uk
      dest: /home/pi/nfs/k8sbak
      version: main

    - role: git
      repo: mortyone/k8sdata_uk
      dest: /home/pi/nfs/k8sdata
      version: main

