- hosts: raspbian_all
  remote_user: pi
  become: yes
#  gather_facts: no
  tasks:
#    - name: set github email
#      git_config:
#        name: user.email
#        scope: global
#        value: mortyone@hotmail.com

#    - name: set github user name
#      git_config:
#        name: user.name
#        scope: global
#        value: "{{ ansible_hostname }}"

    - name: create github directory
      ansible.builtin.file:
        path: /home/pi/github
        state: directory

    - name: set github email as previous doesnt always work
      ansible.builtin.shell: git config --global user.email "gardener@mortylabs.com"

    - name: set github hostname as previous doesn't always work
      ansible.builtin.shell: git config --global user.name "{{ ansible_hostname }}"

#    - name: set github default merge strategy
#      ansible.builtin.shell: git config pull.rebase false



- hosts: raspbian_desktop
  remote_user: pi
  become: yes
  roles:
    - role: git
      repo: mortyone/Pictures
      dest: /home/pi/Pictures
      version: main


- hosts: 192.168.1.18
  remote_user: pi
  become: yes
  gather_facts: no
  roles:
    - role: git
      repo: mortyone/ai_openvino
      dest: /home/pi/github/ai_openvino
      version: main




- hosts: k3s_master
  remote_user: pi
  become: yes
  gather_facts: no

  pre_tasks:
    - name: add ansible aliases
      lineinfile:
        path: /home/pi/.bashrc
        line: '{{ item }}'
        state: present
      with_items:
        - alias ap="ansible-playbook "
        - 'alias al="ansible-lint "'


  roles: 
    - role: git
      repo: mortylabs/ansible
      dest: /home/pi/github/ansible
      version: main

    - role: git
      repo: mKeRix/ansible-playbooks
      dest: /home/pi/github/ansible/room-assistant
      version: master

    - role: git
      repo: mortyone/Music
      dest: /home/pi/Music
      version: main

    - role: git
      repo: mortyone/python
      dest: /home/pi/python
      version: master

    - role: git
      repo: mortyone/kubernetes
      dest: /home/pi/nfs/k8s
      version: main

    - role: git
      repo: mortylabs/MultiRFLinkTCPBridge
      dest: /home/pi/github/MultiRFLinkTCPBridge
      version: main

    - role: git
      repo: mortyone/k8sbak_uk
      dest: /home/pi/nfs/k8sbak
      version: main

    - role: git
      repo: mortyone/k8sdata_uk
      dest: /home/pi/nfs/k8sdata
      version: main

