- hosts: 192.168.1.1[3,7]
  become: yes

  tasks:
    - name: change prompt from green to red
      lineinfile: 
       path=/home/pi/.bashrc
       regexp="^PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] '"
       line="PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] '"
