- hosts: k3s_master
  remote_user: pi
  become: yes
  gather_facts: no
  tasks:
  - name: pull systemd files
    include_role:
      name: systemd
#    vars:
#      github_url: "https://raw.githubusercontent.com/mortyone/systemd-services/master/{{ item }}"
#      systemd_file: "{{ item }}"
    with_items:
      - check_syslog.service
      - multirflink.service
      - mybot.service
#      - rtl_433.service
      - mysoundserver.service


- hosts: room_assistant
  remote_user: pi
  become: yes
  gather_facts: no
  tasks:
  - name: pull systemd files
    include_role:
      name: systemd
    with_items:
      - room-assistant.service


- hosts: rflink_clients
  remote_user: pi
  become: yes
  tasks:
  - name: pull systemd files
    include_role:
      name: systemd
    with_items:
      - rflink.service
