- hosts: raspbian_all
#  remote_user: "{{ user }}"
  remote_user: pi
  become: yes

  tasks:
    - name: sudo apt update   (update package manager repositories cache)
      apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
        autoremove: yes
        cache_valid_time: 3600



